volumes:
  jwtdown-db-data:
    external: true

services:
  fastapi:
    build:
      context: project_gamma
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./project_gamma:/app

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000

  db:
    image: postgres:14.2-bullseye
    volumes:
      - jwtdown-db-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    env_file:
      - ./.env
    ports:
      - 15432:5432
